### ISSUE TITLE
Private?

### ISSUE THREAD

**Issue by pirog** [kalamuna/kala_wysiwyg#1]
reason for this repo being private?

**Comment by andrewmallis** [comment]
it doesn't really do much right now. did not want to advertise this as legit yet.

**Comment by pirog** [comment]
may want to coordinate with @bassettsj and/or @reynoldsalec for assimilation by https://github.com/kalamuna/hot_wysiwyg.

resistance is futile.

**Comment by andrewmallis** [comment]
been public for a bit. hot_wysiwyg is no more
